import { SchemaDefinition } from "../types/schema";

export function generateReadme(schema: SchemaDefinition, orm: string): string {
  return `# ${schema.projectName} Backend

Auto-generated by Schemakit.

## Overview
- Database: ${schema.database}
- ORM: ${orm}
- Tables: ${schema.tables.length}
- API Endpoints: ${schema.tables.length * 5}

## Getting Started

### 1. Install Dependencies
\`\`\`bash
npm install
\`\`\`

### 2. Set Environment Variables
Create a \`.env\` file in the root directory:
\`\`\`env
DATABASE_URL="${schema.database === 'postgresql' ? 'postgresql://user:pass@localhost:5432/db' : '...'}"
PORT=3000
\`\`\`

### 3. Setup Database
Run the initial migration:
\`\`\`bash
# If using raw SQL:
psql $DATABASE_URL < migrations/001_initial.sql
\`\`\`

### 4. Seed Data
\`\`\`bash
# If using raw SQL:
psql $DATABASE_URL < seed.sql
\`\`\`

### 5. Start API Server
\`\`\`bash
npm run dev
\`\`\`

## Architecture
See \`er-diagram.mmd\` for the database visual structure.
See \`openapi.yaml\` for the full API documentation (paste into editor.swagger.io).
`;
}
