import { SchemaDefinition } from "../../types/schema";
import { ManageDatabaseRequestType } from "../../types/request";

export interface NormalizedSchemaContext {
  originalText: string;
  schema?: SchemaDefinition;
  dialect?: 'postgresql' | 'mysql' | 'sqlite';
  formatDetected: 'sql' | 'prisma' | 'drizzle' | 'json' | 'unknown';
  isFallback: boolean;
}

export interface EngineContext {
  request: ManageDatabaseRequestType;
  normalized: NormalizedSchemaContext;
  signal: AbortSignal;
}

export interface EngineResult {
  action: string;
  resultString: string; // The raw script/output generated by the engine
  tablesAffected?: number;
  warnings?: string[];
  notes?: string;
  analysis?: string; // Engine's breakdown of the operation
  downScript?: string; // Optional rollback script
  recommendedIndexes?: string; // Optional indexes string
}
